<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Тест1");
$APPLICATION->SetPageProperty("keywords", "Тест1");
$APPLICATION->SetPageProperty("description", "Тест1");
$APPLICATION->SetTitle("Тест1");
//?><!----><?//$APPLICATION->IncludeComponent(
//	"bitrix:menu",
//	"top_menu",
//	Array(
//		"ALLOW_MULTI_SELECT" => "N",
//		"CHILD_MENU_TYPE" => "left",
//		"COMPONENT_TEMPLATE" => "top_menu",
//		"DELAY" => "N",
//		"MAX_LEVEL" => "2",
//		"MENU_CACHE_GET_VARS" => [],
//		"MENU_CACHE_TIME" => "3600",
//		"MENU_CACHE_TYPE" => "N",
//		"MENU_CACHE_USE_GROUPS" => "N",
//		"ROOT_MENU_TYPE" => "top",
//		"USE_EXT" => "N"
//	)
//);?><!----><?//$APPLICATION->IncludeComponent(
//	"bitrix:news.list",
//	"mainpage_top_slider",
//	Array(
//		"ACTIVE_DATE_FORMAT" => "d.m.Y",
//		"ADD_SECTIONS_CHAIN" => "N",
//		"AJAX_MODE" => "N",
//		"AJAX_OPTION_ADDITIONAL" => "",
//		"AJAX_OPTION_HISTORY" => "N",
//		"AJAX_OPTION_JUMP" => "N",
//		"AJAX_OPTION_STYLE" => "N",
//		"CACHE_FILTER" => "N",
//		"CACHE_GROUPS" => "N",
//		"CACHE_TIME" => "36000000",
//		"CACHE_TYPE" => "N",
//		"CHECK_DATES" => "Y",
//		"DETAIL_URL" => "",
//		"DISPLAY_BOTTOM_PAGER" => "N",
//		"DISPLAY_DATE" => "N",
//		"DISPLAY_NAME" => "N",
//		"DISPLAY_PICTURE" => "Y",
//		"DISPLAY_PREVIEW_TEXT" => "N",
//		"DISPLAY_TOP_PAGER" => "N",
//		"FIELD_CODE" => array("NAME","PREVIEW_TEXT","PREVIEW_PICTURE","DETAIL_TEXT",""),
//		"FILTER_NAME" => "",
//		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
//		"IBLOCK_ID" => "11",
//		"IBLOCK_TYPE" => "50",
//		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
//		"INCLUDE_SUBSECTIONS" => "N",
//		"MESSAGE_404" => "",
//		"NEWS_COUNT" => "10",
//		"PAGER_BASE_LINK_ENABLE" => "N",
//		"PAGER_DESC_NUMBERING" => "N",
//		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
//		"PAGER_SHOW_ALL" => "N",
//		"PAGER_SHOW_ALWAYS" => "N",
//		"PAGER_TEMPLATE" => "",
//		"PAGER_TITLE" => "Новости",
//		"PARENT_SECTION" => "",
//		"PARENT_SECTION_CODE" => "",
//		"PREVIEW_TRUNCATE_LEN" => "",
//		"PROPERTY_CODE" => array("link",""),
//		"SET_BROWSER_TITLE" => "N",
//		"SET_LAST_MODIFIED" => "N",
//		"SET_META_DESCRIPTION" => "N",
//		"SET_META_KEYWORDS" => "N",
//		"SET_STATUS_404" => "N",
//		"SET_TITLE" => "N",
//		"SHOW_404" => "N",
//		"SORT_BY1" => "SORT",
//		"SORT_BY2" => "",
//		"SORT_ORDER1" => "ASC",
//		"SORT_ORDER2" => "",
//		"STRICT_SECTION_CHECK" => "N"
//	)
//);?> <br>
 <br>
 <br>
 <br>
 <br>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	".default", 
	[
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => [
			0 => "",
			1 => "",
		],
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => [
			0 => "",
			1 => "",
		],
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "12",
		"IBLOCK_TYPE" => "50",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => [
			0 => "",
			1 => "",
		],
		"LIST_PROPERTY_CODE" => [
			0 => "",
			1 => "",
		],
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "2",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_MODE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"VARIABLE_ALIASES" => [
			"SECTION_ID" => "SECTION",
			"ELEMENT_ID" => "ELEMENT",
		]
	],
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>